#server配置
server:
  port: 8080

#spring配置
#记得修改一下username和password
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/rightdarkdoc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: root

#mybatis配置
mybatis:
  mapper-locations: classpath:com/rightdarkdoc/mapper/*.xml
  type-aliases-package: com.rightdarkdoc.entity

#log:
